<?php

namespace DoctrineORMModule\Proxy\__CG__\User\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \User\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'recoveredpasswords', 'posts', 'categories', 'medias', 'dogs', 'uniquename', 'email', 'profile', 'password', 'role');
        }

        return array('__isInitialized__', 'id', 'recoveredpasswords', 'posts', 'categories', 'medias', 'dogs', 'uniquename', 'email', 'profile', 'password', 'role');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAdmin', array());

        return parent::isAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniquename($uniquename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniquename', array($uniquename));

        return parent::setUniquename($uniquename);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniquename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniquename', array());

        return parent::getUniquename();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile(\User\Entity\ProfileInterface $profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', array($profile));

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', array());

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function hasProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasProfile', array());

        return parent::hasProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($clearPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($clearPassword));

        return parent::setPassword($clearPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function isThisPassword($unknownClearPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isThisPassword', array($unknownClearPassword));

        return parent::isThisPassword($unknownClearPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function hydrate($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hydrate', array($data));

        return parent::hydrate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, $params)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($method, $params));

        return parent::__call($method, $params);
    }

    /**
     * {@inheritDoc}
     */
    public function getThing($what)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThing', array($what));

        return parent::getThing($what);
    }

    /**
     * {@inheritDoc}
     */
    public function getThings($what)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThings', array($what));

        return parent::getThings($what);
    }

    /**
     * {@inheritDoc}
     */
    public function hasthings($what)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasthings', array($what));

        return parent::hasthings($what);
    }

    /**
     * {@inheritDoc}
     */
    public function addThing($what, $thing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addThing', array($what, $thing));

        return parent::addThing($what, $thing);
    }

    /**
     * {@inheritDoc}
     */
    public function addThings($what, \Doctrine\Common\Collections\Collection $things)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addThings', array($what, $things));

        return parent::addThings($what, $things);
    }

    /**
     * {@inheritDoc}
     */
    public function removeThing($what, $thing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeThing', array($what, $thing));

        return parent::removeThing($what, $thing);
    }

    /**
     * {@inheritDoc}
     */
    public function removeThings($what, \Doctrine\Common\Collections\Collection $things)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeThings', array($what, $things));

        return parent::removeThings($what, $things);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAllThings($what)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAllThings', array($what));

        return parent::removeAllThings($what);
    }

}
