<?php $this->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>
<?php ob_start() ?>
<script type="text/javascript">
(function () {
    // Function will go through all element in the form and
    // and put them to the same state as the selectAllInput
    // checkbox
    function bulkSelectAll() {
        var checkboxes = $("#bulk-action input[name|='<?= $form->getOption('multicheck_element_name')?>[]']");
        var n=checkboxes.length;
        for (var i=0; i<n; i++) {
            checkboxes[i].checked = this.checked;
        }
    };

    // Add the onclick event listener to the selectAllInput
    // checkbox
    var selectAllInput = document.getElementById('bulk-action-input-all');
    if (!selectAllInput) {
        return;
    }
    if (selectAllInput.addEventListener) {
        selectAllInput.addEventListener('click', bulkSelectAll, false); 
    } else if (selectAllInput.attachEvent)  {
        selectAllInput.attachEvent('onclick', bulkSelectAll);
    }

    //Prevent form submition if no items or no action is selected
    var bulkSubmit = $('#bulk-action input[name="submit"]');
    bulkSubmit.on('click', function (e) {
        // Make sure at least one checkbox is checked
        var checkboxes  = $("#bulk-action input[name|='<?= $form->getOption('multicheck_element_name')?>[]']");
        var checkAll    = document.getElementById('bulk-action-input-all');
        var noneChecked = true;

        if (checkAll.checked) {
            noneChecked = false;
        }

        for (var i=0, n=checkboxes.length; i<n; i++) {
            if(checkboxes[i].checked) {
                noneChecked = false;
                break;
            }
        }
        
        if (noneChecked) {
            alert('<?= $this->translate('Please check at least one item') ?>');
            e.preventDefault();
            return;
        }

        // Make sure at least one non empty action is selected 
        var selectOptions = $('#bulk-action select[name*="action-"] option');
        var noneSelected  = true;

        for (var i=0, n=selectOptions.length; i<n; i++) {
            if("" !== selectOptions[i].value && selectOptions[i].selected) {
                noneSelected = false;
                break;
            }
        }

        if (noneSelected) {
            alert('<?= $this->translate('Please select an action') ?>');
            e.preventDefault();
            return;
        }
        //TODO alert, "Are you sure" with a cancel button
    });
})();
</script>

<?php $this->scriptalicious()->addInline('bulk_action', ob_get_clean()) 
    ->addDependency('bulk_action', 'jQuery') ?>

