<ul class="nav navbar-nav">
    <?php foreach ($this->container as $page): ?>
        <?php if(! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>

        <?php $this->lang($page) ?>

        <?php if( ! $page->hasPages()): ?>
        <?php $isPageRouteInSideNavRoutes = $this->conditionalNavigation()->isRouteContainedAndContainerActive($page->getRoute(), array('side_1', 'side_2')) ?>
        <?php $isActive = ($isPageRouteInSideNavRoutes || $page->isActive()) ?>
            <li class="<?= (($isActive)? 'active' : '') ?>">
                <a class="nav-header" href="<?= $page->getHref() ?>">
                    <?php if ($page->iconClass) : ?>
                        <span class="<?= $page->iconClass ?>"></span>
                    <?php endif ?>
                    <span class="text"><?= $this->translate($page->getLabel()) ?></span>
                </a>
            </li>
        <?php else: ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="<?= $page->getHref() ?>">
                    <?php if ($page->iconClass) : ?>
                        <span class="<?= $page->iconClass ?>"></span>
                    <?php endif ?>
                    <span class="text"><?= $this->translate($page->getLabel()) ?></span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                <?php foreach($page->getPages() as $child): ?>
                    <?php // when using partials we need to manually check for ACL conditions ?>
                    <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>

                    <?php $this->lang($child) ?>

                    <?php if (isset($child->divider) && 'above' === $child->divider): ?>
                        <li role="presentation" class="divider"></li>
                    <?php endif;?>
                    <?php if (isset($child->header)): ?>
                        <li role="presentation" class="dropdown-header"><?= $child->header?></li>
                    <?php endif;?>
                    <li>
                        <a href="<?= $child->getHref() ?>">
                            <?= $this->translate($child->getLabel(), 'sc') ?>
                        </a>
                    </li>
                    <?php if (isset($child->divider) && 'below' === $child->divider): ?>
                        <li class="divider"></li>
                    <?php endif;?>
                <?php endforeach ?>
                </ul>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
<?php require_once  __DIR__ . '/../../../Lang/view/partial/langnav.phtml' ?>
